{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "mediqueue-chart.labels" . | nindent 4 }}
{{- end }}

