{{- if .Values.networkPolicy.enabled }}
# Network Policy for API - allows ingress from frontend and gateway
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mediqueue-chart.api.fullname" . }}
  namespace: {{ include "mediqueue-chart.namespace" . }}
  labels:
    {{- include "mediqueue-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  podSelector:
    matchLabels:
      {{- include "mediqueue-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: frontend
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: worker
      ports:
        - protocol: TCP
          port: {{ .Values.api.service.targetPort }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: postgres
      ports:
        - protocol: TCP
          port: {{ .Values.postgres.service.port }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: redis
      ports:
        - protocol: TCP
          port: {{ .Values.redis.service.port }}
    # Allow DNS resolution
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53

# Network Policy for Worker - needs access to postgres and redis
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mediqueue-chart.worker.fullname" . }}
  namespace: {{ include "mediqueue-chart.namespace" . }}
  labels:
    {{- include "mediqueue-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  podSelector:
    matchLabels:
      {{- include "mediqueue-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: postgres
      ports:
        - protocol: TCP
          port: {{ .Values.postgres.service.port }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: redis
      ports:
        - protocol: TCP
          port: {{ .Values.redis.service.port }}
    # Allow DNS resolution
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53

# Network Policy for PostgreSQL - only allow connections from api and worker
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mediqueue-chart.postgres.fullname" . }}
  namespace: {{ include "mediqueue-chart.namespace" . }}
  labels:
    {{- include "mediqueue-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  podSelector:
    matchLabels:
      {{- include "mediqueue-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: api
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: worker
      ports:
        - protocol: TCP
          port: {{ .Values.postgres.service.port }}

# Network Policy for Redis - only allow connections from api and worker
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mediqueue-chart.redis.fullname" . }}
  namespace: {{ include "mediqueue-chart.namespace" . }}
  labels:
    {{- include "mediqueue-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  podSelector:
    matchLabels:
      {{- include "mediqueue-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: api
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: worker
      ports:
        - protocol: TCP
          port: {{ .Values.redis.service.port }}
{{- end }}

