{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mediqueue-chart.redis.fullname" . }}
  namespace: {{ include "mediqueue-chart.namespace" . }}
  labels:
    {{- include "mediqueue-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "mediqueue-chart.redis.fullname" . }}
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      {{- include "mediqueue-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "mediqueue-chart.labels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      {{- include "mediqueue-chart.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "mediqueue-chart.serviceAccountName" . }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          {{- if .Values.redis.auth.enabled }}
          command:
            - redis-server
            - --requirepass
            - $(REDIS_PASSWORD)
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mediqueue-chart.redis.secretName" . }}
                  key: {{ .Values.redis.auth.secretKey }}
          {{- end }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
              protocol: TCP
          {{- if .Values.redis.persistence.enabled }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
          {{- end }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          livenessProbe:
            {{- if .Values.redis.auth.enabled }}
            exec:
              command:
                - sh
                - -c
                - redis-cli -a $REDIS_PASSWORD ping | grep PONG
            {{- else }}
            exec:
              command:
                - redis-cli
                - ping
            {{- end }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            {{- if .Values.redis.auth.enabled }}
            exec:
              command:
                - sh
                - -c
                - redis-cli -a $REDIS_PASSWORD ping | grep PONG
            {{- else }}
            exec:
              command:
                - redis-cli
                - ping
            {{- end }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          {{- toYaml .Values.redis.persistence.accessModes | nindent 10 }}
        {{- if .Values.redis.persistence.storageClass }}
        storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
  {{- end }}
{{- end }}
